### ISSUE TITLE
Questions about leafcutter annotation files

### ISSUE THREAD

**Issue by yangchuhua** [eQTL-Catalogue/qcnorm#15]
No question anymore. I have found them in https://zenodo.org/record/3366280#.Yy4VfOzP3UJ.

**Comment by kauralasoo** [comment]
You can find the latest version also in here:
http://ftp.ebi.ac.uk/pub/databases/spot/eQTL/references/rnaseq_complete_reference_290322.tar.gz

Best,
Kaur

**Comment by yangchuhua** [comment]
> You can find the latest version also in here: http://ftp.ebi.ac.uk/pub/databases/spot/eQTL/references/rnaseq_complete_reference_290322.tar.gz
> 
> Best, Kaur

Thank you very much.
