### ISSUE TITLE
How to install this qcnorm and download test files 

### ISSUE THREAD

**Issue by zhoudreames** [eQTL-Catalogue/qcnorm#17]
I download qcnorm by [Releases](https://github.com/eQTL-Catalogue/qcnorm/releases), then decompressed it.  there are some errors when I run the run_rnaseq_norm.sh:
```
WARN: There's no process matching config selector: refVCFtoBED
WARN: There's no process matching config selector: removeFamilyFromRef
WARN: There's no process matching config selector: removeDublFromRef
WARN: There's no process matching config selector: sampleVCftoBED
WARN: There's no process matching config selector: calculateRelatednessMatrix
WARN: There's no process matching config selector: getSNPsFromRef
WARN: There's no process matching config selector: extractSharedSNPsFromSampleGen
WARN: There's no process matching config selector: extractSharedSNPsFromRefGen
WARN: There's no process matching config selector: calcKinsMatrices
WARN: There's no process matching config selector: calcRefPcaAndLoads
WARN: There's no process matching config selector: mapSampleGenToRef
WARN: There's no process matching config selector: plotPCA
WARN: There's no process matching config selector: normalise_RNAseq_txrev
No such file: /gpfs/hpc/projects/genomic_references/annotations/eQTLCatalogue/v0.1/phenotype_metadata/gene_counts_Ensembl_96_phenotype_metadata.tsv.gz


No such file: /gpfs/hpc/home/kerimov/SampleArcheology/studies/cleaned/Alasoo_2018_test.tsv


No such file: /gpfs/hpc/home/kerimov/qcnorm/results/Alasoo_2018/pop_assign/projections_comb.tsv


No such file: /gpfs/hpc/projects/eQTLCatalogue/processed/Alasoo_2018/featureCounts/merged_gene_counts.txt
```
I don't know if I installed it successfully， and how to download the missing test file. Thanks

**Comment by zhoudreames** [comment]
@kauralasoo @kerimoff  can you help me? Thanks~

**Comment by kauralasoo** [comment]
Take a look at this tutorial first:
https://github.com/eQTL-Catalogue/eQTL-Catalogue-resources/blob/master/tutorials/workflow_execution.md

**Comment by yangchuhua** [comment]
> Take a look at this tutorial first: https://github.com/eQTL-Catalogue/eQTL-Catalogue-resources/blob/master/tutorials/workflow_execution.md

I have checked this tutorials and found that there is no `./genomic_references/1000G/pop_assign/GRCh38_renamed_ids_no_multiallelic.vcf.gz`.

I wonder if you could share this file.

Thank you very much.

Best,
Chuhua

**Comment by kauralasoo** [comment]
Sorry, I have not had a chance to upload these files to our FTP yet. In the mean time, please take a look here:
https://drive.google.com/drive/folders/16qyR1b0NgoWDxSqJWOKFQSk3yNWuNrM8?usp=sharing

Best,
Kaur

**Comment by yangchuhua** [comment]
Dear Kaur,


Thanks for your reply very much.


It's helpful. Have a nice weekend.


Best,

Chuhua


-----------------------------

Chuhua Yang


Deutsches Herzzentrum München

Technische Universität München

Lazarettstraße 36

80636 München

Telefon: +34-610918421

________________________________
